_base_:
  - '../_base_/datasets/reds_deint.yaml'
  - '../_base_/schedules/schedule_adamw_cos.yaml'
  - '../_base_/losses/mvdnet_loss.yaml'

model:
  mid: 64
  num_blocks: 10 # 减少层数，追求极致速度
  lookahead: 2
  propagation_order: 1
  scale: 2
  feat_act_cfg: "LeakyReLU"
  body_act_cfg: "PReLU"
  
  feature_extractor_cfg: 
    type: 'SimpleFeatureExtractor' # 最简单的特征提取
    in_channels: 4
    nf: 64
  mv_refiner_cfg: 
    type: 'VanillaMVRefiner' # 不加任何引导的简单光流修正
  gmc_cfg: 
    type: 'IdentityGMC' # ！！关闭全局背景补偿！！
  residual_block_cfg: 
    type: 'StandardResidualBlock' # 标准残差块
    
  foward_backward_fusion_cfg: 
    type: 'BasicConcatFusion'
  h_prop_current_feat_fusion_cfg: 
    type: 'SoftGateAdaptiveFusion'
  first_2nd_order_fusion_cfg: 
    type: 'SimpleAverageFusion' # 简单平均，不使用注意力
  deint_up_cfg: 
    type: 'DeintShufflePack'
    scale_factor: 2
dataset:
  train:
    root_dir: '/localscratch/sihanuo.57175028.0/REDS_data'
  val:
    root_dir: '/localscratch/sihanuo.57175028.0/REDS_data'
