_base_:
  - '../_base_/datasets/reds_deint.yaml'
  - '../_base_/schedules/schedule_adamw_cos.yaml'
  - '../_base_/losses/mvdnet_loss.yaml'

model:
  mid: 64
  num_blocks: 15
  lookahead: 2
  propagation_order: 1
  scale: 2
  feat_act_cfg: "LeakyReLU"
  body_act_cfg: "PReLU"
  
  feature_extractor_cfg: 
    type: 'ResidualFeatureExtractor'
    in_channels: 4
    num_blocks: 5
    nf: 64
  mv_refiner_cfg: 
    type: 'LiteConvexMVRefiner' # ！！最强光流凸上采样精调！！
  gmc_cfg: 
    type: 'GMC' # ！！开启 RANSAC 背景剥离补偿！！
  residual_block_cfg: 
    type: 'ChannelAttentionBlock' # ！！带有 RepConv 和 注意力的最强 Block！！
    deploy: false # 训练时必须为 false
    
  foward_backward_fusion_cfg: 
    type: 'BasicConcatFusion'
  h_prop_current_feat_fusion_cfg: 
    type: 'MotionAdaptiveFusion' # 升级版动静融合
  first_2nd_order_fusion_cfg: 
    type: 'DeinterlacingMultiOrderFusion'
  deint_up_cfg: 
    type: 'DeintShufflePack'
    scale_factor: 2
dataset:
  train:
    root_dir: '/home/mcrlab/Documents/REDS_lmdb'
  val:
    root_dir: '/home/mcrlab/Documents/REDS_lmdb'
