_base_:
  - '../_base_/datasets/reds_deint.yaml'
  - '../_base_/schedules/schedule_adamw_cos.yaml'
  - '../_base_/losses/mvdnet_loss.yaml'

model:
  mid: 32
  num_blocks: 10
  lookahead: 2
  propagation_order: 1
  scale: 2
  feat_act_cfg: "LeakyReLU"
  body_act_cfg: "LeakyReLU"
  
  feature_extractor_cfg: 
    type: 'ResidualFeatureExtractor' # 💡 升级点 5.1：换成强力特征提取
    in_channels: 4
    num_blocks: 5
    nf: 32
  mv_refiner_cfg: 
    type: 'LiteConvexMVRefiner'
  gmc_cfg: 
    type: 'FastGPUGMC'
  residual_block_cfg: 
    type: 'ChannelAttentionBlock' # 💡 升级点 5.2：换用带通道注意力的 RepConv
    deploy: false # 训练时必须为 false
    
  foward_backward_fusion_cfg: 
    type: 'BasicConcatFusion'
  h_prop_current_feat_fusion_cfg: 
    type: 'MotionAdaptiveFusion' 
  first_2nd_order_fusion_cfg: 
    type: 'DeinterlacingMultiOrderFusion'
  deint_up_cfg: 
    type: 'DeintShufflePack'
    scale_factor: 2