# 实验基本配置
experiment:
  name: "mvsr_baseline_v1"
  data_root: "/home/sihanuo/scratch/SihanZhangData"

# 训练参数
train:
  seq_len: 5
  crop_lr: 64
  batch_size: 16
  lr: 0.0002
  # 建议把 clip_grad 和 vis_freq 也写在这里，方便控制
  clip_grad: 1.0 
  vis_freq: 10

# 模型参数 (只需保留这一个)
model:
  type: "UnifiedMVSR"  # 对应代码里的 class UnifiedMVSR
  args:
    mid: 64
    blocks: 15
    mv_mode: "physical"
    correct_offset: true
    use_adaptive_fusion: true # 记得加上这个开关
    refiner_cfg:
      # 注意：代码里必须有 @register_component class MVRefiner_Adaptive
      type: "MVRefiner_Adaptive" 
      args:
        mid: 64

# Loss 配置
loss_config:
  use_sr: true
  w_sr: 1.0
  
  use_temp_short: true
  w_temp_short: 0.05
  
  use_temp_long: true
  w_temp_long: 0.5
  
  use_flow: true
  w_photo: 0.01
  w_smooth: 0.001